-- MySQL Script generated by MySQL Workbench
-- Fri Jun 10 10:32:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LeoMoschnerSchedule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LeoMoschnerSchedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LeoMoschnerSchedule` DEFAULT CHARACTER SET utf8 ;
USE `LeoMoschnerSchedule` ;

-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`calendar` (
  `idCalendar` INT NOT NULL,
  PRIMARY KEY (`idCalendar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`shifts` (
  `idShifts` INT NOT NULL AUTO_INCREMENT,
  `calendario_ID` INT NOT NULL,
  PRIMARY KEY (`idShifts`, `calendario_ID`),
  INDEX `fk_turnos_calendario1_idx` (`calendario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_turnos_calendario1`
    FOREIGN KEY (`calendario_ID`)
    REFERENCES `LeoMoschnerSchedule`.`calendar` (`idCalendar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`professors` (
  `idProfessors` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`subjects` (
  `idsubjects` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `professors_ID` INT NOT NULL,
  PRIMARY KEY (`idsubjects`),
  INDEX `fk_subjects_professors1_idx` (`professors_ID` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_professors1`
    FOREIGN KEY (`professors_ID`)
    REFERENCES `LeoMoschnerSchedule`.`professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`group` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `limitAmount` INT NULL,
  `shifts_ID` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `fk_group_shifts1_idx` (`shifts_ID` ASC) VISIBLE,
  CONSTRAINT `fk_group_shifts1`
    FOREIGN KEY (`shifts_ID`)
    REFERENCES `LeoMoschnerSchedule`.`shifts` (`idShifts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`students` (
  `idstudents` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `group_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idstudents`, `group_idGrupo`),
  INDEX `fk_students_group1_idx` (`group_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_students_group1`
    FOREIGN KEY (`group_idGrupo`)
    REFERENCES `LeoMoschnerSchedule`.`group` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`classrooms` (
  `idClassrooms` INT NOT NULL AUTO_INCREMENT,
  `size` INT NULL,
  `available` TINYINT NULL,
  PRIMARY KEY (`idClassrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`studentsSubjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`studentsSubjects` (
  `idStudentsSubjects` INT NOT NULL AUTO_INCREMENT,
  `students_ID` INT NOT NULL,
  `subjects_ID` INT NOT NULL,
  `grade` INT NULL,
  PRIMARY KEY (`idStudentsSubjects`, `subjects_ID`),
  INDEX `fk_students_has_subjects_subjects1_idx` (`subjects_ID` ASC) VISIBLE,
  INDEX `fk_studentsSubjects_students1_idx` (`students_ID` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_subjects_subjects1`
    FOREIGN KEY (`subjects_ID`)
    REFERENCES `LeoMoschnerSchedule`.`subjects` (`idsubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studentsSubjects_students1`
    FOREIGN KEY (`students_ID`)
    REFERENCES `LeoMoschnerSchedule`.`students` (`idstudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`modules` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `subjects_ID` INT NOT NULL,
  `classrooms_ID` INT NOT NULL,
  `turnos_ID` INT NOT NULL,
  PRIMARY KEY (`idModulo`, `subjects_ID`, `turnos_ID`),
  INDEX `fk_Modulo_subjects1_idx` (`subjects_ID` ASC) VISIBLE,
  INDEX `fk_Modulo_classrooms1_idx` (`classrooms_ID` ASC) VISIBLE,
  INDEX `fk_modules_turnos1_idx` (`turnos_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_subjects1`
    FOREIGN KEY (`subjects_ID`)
    REFERENCES `LeoMoschnerSchedule`.`subjects` (`idsubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modulo_classrooms1`
    FOREIGN KEY (`classrooms_ID`)
    REFERENCES `LeoMoschnerSchedule`.`classrooms` (`idClassrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modules_turnos1`
    FOREIGN KEY (`turnos_ID`)
    REFERENCES `LeoMoschnerSchedule`.`shifts` (`idShifts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LeoMoschnerSchedule`.`days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LeoMoschnerSchedule`.`days` (
  `idDays` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  `turnos_idturnos` INT NOT NULL,
  PRIMARY KEY (`idDays`, `turnos_idturnos`),
  INDEX `fk_days_turnos1_idx` (`turnos_idturnos` ASC) VISIBLE,
  CONSTRAINT `fk_days_turnos1`
    FOREIGN KEY (`turnos_idturnos`)
    REFERENCES `LeoMoschnerSchedule`.`shifts` (`idShifts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
